# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\works\JBL\app\View\timelog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeLog(object):
    def setupUi(self, TimeLog):
        TimeLog.setObjectName("TimeLog")
        TimeLog.resize(962, 660)
        TimeLog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(TimeLog)
        self.widget.setGeometry(QtCore.QRect(50, 20, 321, 581))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ListWidget = ListWidget(self.widget)
        self.ListWidget.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    background-color: rgb(249, 249, 249);\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"ListView::indicator:hover,\n"
"ListWidget::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"ListView::indicator:pressed,\n"
"ListWidget::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"ListView::indicator:checke,\n"
"ListWidget::indicator:checked,\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"ListView::indicator:checked,\n"
"ListWidget::indicator:checked {\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:checked:hove,\n"
"ListWidget::indicator:checked:hover,\n"
"ListView::indicator:indeterminate:hover,\n"
"ListWidget::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"ListView::indicator:checked:presse,\n"
"ListWidget::indicator:checked:pressed,\n"
"ListView::indicator:indeterminate:pressed,\n"
"ListWidget::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"ListView::indicator:disabled,\n"
"ListWidget::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"ListView::indicator:checked:disable,\n"
"ListWidget::indicator:checked:disabled,\n"
"ListView::indicator:indeterminate:disabled,\n"
"ListWidget::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.ListWidget.setObjectName("ListWidget")
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget.addItem(item)
        self.gridLayout.addWidget(self.ListWidget, 1, 0, 1, 1)
        self.ListWidget_2 = ListWidget(self.widget)
        self.ListWidget_2.setStyleSheet("ListView,\n"
"ListWidget {\n"
"    background: transparent;\n"
"    outline: none;\n"
"    border: none;\n"
"    /* font: 13px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
"    selection-background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    padding-left: 4px;\n"
"    padding-right: 4px;\n"
"    background-color: rgb(249, 249, 249);\n"
"}\n"
"\n"
"ListView::item,\n"
"ListWidget::item {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    padding-left: 11px;\n"
"    padding-right: 11px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"\n"
"ListView::indicator,\n"
"ListWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"ListView::indicator:hover,\n"
"ListWidget::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"ListView::indicator:pressed,\n"
"ListWidget::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"ListView::indicator:checke,\n"
"ListWidget::indicator:checked,\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"ListView::indicator:checked,\n"
"ListWidget::indicator:checked {\n"
"    image: url(:/qfluentwidgets/images/check_box/Accept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:indeterminate,\n"
"ListWidget::indicator:indeterminate {\n"
"    image: url(:/qfluentwidgets/images/check_box/PartialAccept_white.svg);\n"
"}\n"
"\n"
"ListView::indicator:checked:hove,\n"
"ListWidget::indicator:checked:hover,\n"
"ListView::indicator:indeterminate:hover,\n"
"ListWidget::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"ListView::indicator:checked:presse,\n"
"ListWidget::indicator:checked:pressed,\n"
"ListView::indicator:indeterminate:pressed,\n"
"ListWidget::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"ListView::indicator:disabled,\n"
"ListWidget::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"ListView::indicator:checked:disable,\n"
"ListWidget::indicator:checked:disabled,\n"
"ListView::indicator:indeterminate:disabled,\n"
"ListWidget::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.ListWidget_2.setObjectName("ListWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.ListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.ListWidget_2.addItem(item)
        self.gridLayout.addWidget(self.ListWidget_2, 1, 1, 1, 1)
        self.BodyLabel = BodyLabel(self.widget)
        self.BodyLabel.setMinimumSize(QtCore.QSize(0, 28))
        self.BodyLabel.setMaximumSize(QtCore.QSize(16777215, 28))
        self.BodyLabel.setStyleSheet("background-color: rgba(51, 51, 51, 0.1);")
        self.BodyLabel.setProperty("pixelFontSize", 15)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 0, 0, 1, 1)
        self.BodyLabel_2 = BodyLabel(self.widget)
        self.BodyLabel_2.setMinimumSize(QtCore.QSize(0, 28))
        self.BodyLabel_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.BodyLabel_2.setStyleSheet("background-color: rgba(51, 51, 51, 0.1);")
        self.BodyLabel_2.setProperty("pixelFontSize", 15)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout.addWidget(self.BodyLabel_2, 0, 1, 1, 1)

        self.retranslateUi(TimeLog)
        QtCore.QMetaObject.connectSlotsByName(TimeLog)

    def retranslateUi(self, TimeLog):
        _translate = QtCore.QCoreApplication.translate
        TimeLog.setWindowTitle(_translate("TimeLog", "Form"))
        __sortingEnabled = self.ListWidget.isSortingEnabled()
        self.ListWidget.setSortingEnabled(False)
        item = self.ListWidget.item(0)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget.item(1)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget.item(2)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget.item(3)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget.item(4)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget.item(5)
        item.setText(_translate("TimeLog", "新建项目"))
        self.ListWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.ListWidget_2.isSortingEnabled()
        self.ListWidget_2.setSortingEnabled(False)
        item = self.ListWidget_2.item(0)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget_2.item(1)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget_2.item(2)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget_2.item(3)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget_2.item(4)
        item.setText(_translate("TimeLog", "新建项目"))
        item = self.ListWidget_2.item(5)
        item.setText(_translate("TimeLog", "新建项目"))
        self.ListWidget_2.setSortingEnabled(__sortingEnabled)
        self.BodyLabel.setText(_translate("TimeLog", "    项目列表"))
        self.BodyLabel_2.setText(_translate("TimeLog", "    任务列表"))
from qfluentwidgets import BodyLabel, ListWidget
