# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\works\JBL\app\View\UI\updata.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JBL_Updata(object):
    def setupUi(self, JBL_Updata):
        JBL_Updata.setObjectName("JBL_Updata")
        JBL_Updata.resize(420, 163)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(JBL_Updata.sizePolicy().hasHeightForWidth())
        JBL_Updata.setSizePolicy(sizePolicy)
        JBL_Updata.setMinimumSize(QtCore.QSize(420, 163))
        JBL_Updata.setMaximumSize(QtCore.QSize(420, 163))
        self.verticalLayout = QtWidgets.QVBoxLayout(JBL_Updata)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(JBL_Updata)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DisplayLabel = DisplayLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DisplayLabel.sizePolicy().hasHeightForWidth())
        self.DisplayLabel.setSizePolicy(sizePolicy)
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.horizontalLayout.addWidget(self.DisplayLabel)
        self.ProgressRing = ProgressRing(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProgressRing.sizePolicy().hasHeightForWidth())
        self.ProgressRing.setSizePolicy(sizePolicy)
        self.ProgressRing.setStrokeWidth(6)
        self.ProgressRing.setObjectName("ProgressRing")
        self.horizontalLayout.addWidget(self.ProgressRing)
        self.verticalLayout.addWidget(self.frame)
        self.StrongBodyLabel = StrongBodyLabel(JBL_Updata)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout.addWidget(self.StrongBodyLabel)

        self.retranslateUi(JBL_Updata)
        QtCore.QMetaObject.connectSlotsByName(JBL_Updata)

    def retranslateUi(self, JBL_Updata):
        _translate = QtCore.QCoreApplication.translate
        JBL_Updata.setWindowTitle(_translate("JBL_Updata", "Form"))
        self.DisplayLabel.setText(_translate("JBL_Updata", "正在更新"))
        self.StrongBodyLabel.setText(_translate("JBL_Updata", "Strong body label"))
from qfluentwidgets import DisplayLabel, ProgressRing, StrongBodyLabel
